default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: ruff check
        language: system
        pass_filenames: false
        args: [ --fix ]
      - id: format
        name: format
        entry: ruff format
        language: system
        pass_filenames: false
